language: node_js

sudo: false

dist: trusty

node_js:
  - '10'

addons:
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "b6rK9e3FJ6GUWyQ1Atqcy/3zZ0Xrlh6CNakoqtEkRxVP7Bm9u/Z5zRZRrk8RMfw2oxUUDoe17iGUNATf1BOZu6Lcm1/gTyShz+LX6Dv+2eeiucDZbzwYwzg5v11bxqQp85q2BD19jkK9djyyEkzCv0MuKB4lmHeGJuEowWvtfCFVA22ZSo4VqnkO1laXE+/FHE6Y4T+Rlpb0t96EK3cED8j7Pj16jSpmHQefqhZ/T13pI95qQUQy9YnW+vaTdcpzMTxYD0SALJ/IL+0gNNZbDzLvjWxwL4x9rI4scwrTQGK9+St2+ZwXKf79ABxd7GE+C7nX76Hfu7Ro5Re4dOvNzMKvmM92oi2M04lvDvw1JC/SiHOpnA9v/qSFCRflUbkx/Z0GGHGOkCpmlZ3NNkcnPO5JG2eyWlM3qlNfhy1OxAIvnbNcVDOxvZsSoV1+nOxsYNGpVzyLPrUNuIiSnD3iYMTQaBbqi3Ms5XHnWHqLuivR61zTWUYRLdn/GITcnT2HuLAc7no6vBnp1uc7QCL2/9t9ktFEsWSubusTJd7/ZS6Y96wm8PEE7sjLFBUuOMsP1xyaksX2fnczgkNYrjACeIc3ohrBNxZbgQTdtr56Kg35QtF+DpxMbeo4yFnETfevYBQeUizwZXSvmwaT/J06KN9mnG/GkmviHFetU6itPWM="

script:
  - sonar-scanner

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: PopSauce.user.js
  skip_cleanup: true
  on:
    tags: true

git:
  depth: 1