language: node_js

sudo: false

dist: trusty

node_js:
  - '10'

addons:
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "Yr5FGTYtRAWedTHircR4ZArpdScDRpVmbWP38PvP597AB8Fcvzm+GYJTJSFpmdhJPhThQRVYoYonKOWIJZRG2MAykuXuLNRyVtkT4Omjh8UgnkRlofDALPSJ32O6KepoWmxFyVfA0Qtja4WauDCge/WAkGCp94KxptySGYe8rGGYkGORf2LcEOazvuvoQDwCqq5QGCAas59CW4FYyQFUNkwBJl+jUHDitL2tP9ZRM1chXkkxAAaLjruNQjHCVkZ8u3P58GNYBeFsB9CMuC1419DzO70WXR6tnvQ2oEayWAs1sYxgJBqjc+Wy5eOL9Kv4CeMsEUBnrR23hScslI13EmaQKv1egDJ2+NYGeunely3sxnsTNfNsJUEWaG/VXs0CFGyzytjqdSqi4gUnURrNh2buk4+gzyScOh2XaT4r+b7jbPbssvFJHN3qLBblZSms+32fUDO0EQc3509H/JRnHK8DhjGsV79v/jE5S895Hu1kwrWpmJ4n1v+x/iP2cbXp33yTcRcFj67/FnT/AbQ0JgARiJ3N7I3p3C/vYU1iS17L6VkZvywtFeb+qrLqYdYHPT8JX1xZbsp521Mx/9IRa6hE0uQPv/+BrV2maDdVO42KzRhcBqlh0vhqHCyOP7v7k/D+B/1amLQtHrRnc+tTHxI5NHCO+h8IOFnOuPHCT1Q="

script:
  - sonar-scanner

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: BombParty.user.js
  skip_cleanup: true
  on:
    tags: true

git:
  depth: 1