language: node_js

sudo: false

dist: trusty

node_js:
  - '10'

addons:
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "b7n0Jj4XOeQpdtYB/oJM9BJMTOHKb19F1UNuGA8Tx6gRlzoF93bneK0EUrhXf6+KrK5MZSS62JVTfQd75m/Lau8/B664KkD7kEWusooTuojEN0gIurH9sqk/YlJ6oJ3Xfe5okE9tbyUOQtITjfVguaiysxqn3XVtRgIyOopkXhgM0qvob10iuzrbJxoPcc1W48ajgLktI4wEbHptUKUVzzZCHGNHOMdAGkth9IfG8r7KaFQfOG84ZTIX5VetOm+yDQ5hZ1wQnGqcLOmZzUPy5FsOArrk6LQeMK48rSsC47frp76ypN8DkaXGBXHwfHXKFiYIt+pHmvyvTlWlIfH09FD7OisM25OfPHCM3geLBbgTzcTHCy3UxH7CY0MKKTnq78h629nleNb/4ZoBcNfiINLfLDTY7TuqLNLP3Vywk1acAFfE83/Dcm81Uz+ZvYuDN9mtUD957TgXlRAqUN6U+unm7q1ivJnsaPJRGoWgooWGg/rpPFv0bwxq8O+QtSle7mSFbfUv+3LUaKOenGmURyP3DiVwHelNpPbQ9euhuVdE9s+LA6iaG0DryyFz7Ta0bxRboNLcz3aE2JS+9WdOO2EJjycFSK244n9NrAzB9/kMct0jlwfAO1HoYR/40x014cbRDaekWVfe6ixKzDrOsITFNVTn9fsUM8WH60xPqIQ="

script:
  - sonar-scanner

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: PopSauce.user.js
  skip_cleanup: true
  on:
    tags: true

git:
  depth: 1