language: node_js

sudo: false

dist: trusty

node_js:
  - '10'

addons:
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "K9181pr5MMtkuiq8zjlARgY/vcZ8NQ738nRLF8BhHxu6Nb2ajY6049O9Ixhl9E6ZpxIr42pUpety8BeAhJuFUqmOWjSMw7uuTT33F5BM2UgHyyItIn0zCmZrLeYZjtMjAh+ZGxqXC6g4Y0o/sTIwxvvHNnwh2rJDt5HjJ9ieweKCaquk7vFvw0yfBXvzhNsWtAitRuPwkU5TdsBnDau/+ZZGkxqKWBBAnAdTZQXJN9K2jBzRzQhna7F8nyBHNb1NX8+TZgq9luaMxIBlW8t16McfYzeGGRuN8kfKvIavWI+/757sI+WFO/WYYjv9gfU7TTgmWlZgtlrZs2aNtmQpADodXrRXg3fDfWW7/ghx78uBzV/0d2ElbQYr69jc1OyE2+Yq2d+W4COwSXSfeIC4AsUOWfeD+XF/XUaNWK3dDG0G91YYvU7od5iTlAeicaDhA//WN7AfwiXJJ9w1ZNQUxtApCDLF6gtLmkzkGqszm1Ewk+hnGKBNkB+FrafX56H+0B8WHga5mVw8FcQc8tB4f7MJyqFRf6oBu3Dhraucq5bIFt+Khw7ucf6aikkZAgJnGMqAGOvdLlhohiQ0BE2QgV0lp+Uqr7SNPw6my0Xy1XybN/OQCOKLnI0YeZths3o9aAcI8AHsZKiRPooExQt4YO1d47re4pcwMmAi7zQChgY="

script:
  - sonar-scanner

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: PopSauce.user.js
  skip_cleanup: true
  on:
    tags: true

git:
  depth: 1